POST /services HTTP/1.1
Host: localhost:8080
Authorization: 07b4e8ed58a6f97897b03843474c8cc981d154ffe45b10ef88a9f127b15c5c56
Content-Type: application/json
Content-Length: 92

{
    "type": "beacon",
    "url": "https://staging-elixirbeacon.rahtiapp.fi/service-info"
}