name: S2I Build Check

on: [pull_request]

jobs:
  build:
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    name: Integration Tests
    
    steps:
    - uses: actions/checkout@v4

    - name: Install requirements
      run: |
        wget https://github.com/openshift/source-to-image/releases/download/v1.2.0/source-to-image-v1.2.0-2a579ecd-linux-amd64.tar.gz
        tar -xvf source-to-image-v1.2.0-2a579ecd-linux-amd64.tar.gz
        sudo cp s2i /usr/local/bin
    - name: Build image
      run:  |
        s2i build . centos/python-38-centos7 cscfi/beacon-network
